In [ ]:
# create array of days of the year.  arange will just go in order, 0 - 365
days = np.arange(365)
#print(days)
# this gets a mask of summer days (true / false results based on condition)
#   172 = start of summer.  262 = end of summer
summer = (days > 172) & (days < 262)
#print(summer)
# proving mask gets just summer values, by using summer as indices to get precipitation values
#precip_inches[summer].size
#precip_inches[summer]

# creating array of only rainy day values (precipitation greater than 0)
rainy_day_index = precip_inches[precip_inches > 0.0]
#print(rainy_day_index)

# creating mask of days with rain (true / false results based on condition)
rainy_days = (precip_inches > 0.0)

print(f"Average rain for year: {np.mean(precip_inches)}")
print(f"Median rain for year: {np.median(precip_inches)}")

print(f"Average rainy day using resultant np array: {np.mean(rainy_day_index)}")
print(f"Average rainy day using mask: {np.mean(precip_inches[rainy_days])}")

print(f"Median rainy day using resultant np array: {np.median(rainy_day_index)}")
print(f"Median rainy day using mask: {np.median(precip_inches[rainy_days])}")

print(f"Average rain in summer: {np.mean(precip_inches[summer])}")
print(f"Median rain in summer: {np.median(precip_inches[summer])}")
print(f"Max rain on a summer day: {np.max(precip_inches[summer])}")

#print(f"Average rainy days not in summer: {np.mean(precip_inches[(precip_inches > 0.0) & ~summer])}")
print(f"Average rainy days not in summer: {np.mean(precip_inches[rainy_days & ~summer])}")

#print(f"Median rainy days not in summer: {np.median(precip_inches[(precip_inches > 0.0) & ~summer])}")
print(f"Median rainy days not in summer: {np.median(precip_inches[rainy_days & ~summer])}")

In [9]:
import numpy as np 

name = ['Alice', 'Bob', 'Cathy', 'Doug']
age = [25, 45, 37, 19]
weight = [55.0, 85.5, 68.0, 61.5]

x = np.zeros(4, dtype=int)
print(x)

data = np.zeros(4, dtype={
    'names':('name', 'age', 'weight'),
    'formats':('U10', 'i4', 'f8')
    }
    )
print(data)
print(data.dtype)

data['name'] = name
print(data)
data['age'] = age
data['weight'] = weight
print(data)

print(data['name'])
print(data[0])

print(data['age'] < 30)
print(data[(data['age'] < 30)])

data[data['age'] < 30]['name']

[0 0 0 0]
[('', 0, 0.) ('', 0, 0.) ('', 0, 0.) ('', 0, 0.)]
[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')]
[('Alice', 0, 0.) ('Bob', 0, 0.) ('Cathy', 0, 0.) ('Doug', 0, 0.)]
[('Alice', 25, 55. ) ('Bob', 45, 85.5) ('Cathy', 37, 68. )
 ('Doug', 19, 61.5)]
['Alice' 'Bob' 'Cathy' 'Doug']
('Alice', 25, 55.)
[ True False False  True]
[('Alice', 25, 55. ) ('Doug', 19, 61.5)]


array(['Alice', 'Doug'], dtype='<U10')

In [30]:
import pandas as pd 
data = pd.Series([23, 45, 87, 32], index = ['bob', 'carrie', 'dave', 'apple'])

#print(data)
#print(data[0])
#print(data['bob'])

print(data[(data > 80) | (data < 30)])
print(data[['bob', 'apple']])

bob     23
dave    87
dtype: int64
bob      23
apple    32
dtype: int64


In [36]:
population_dict = {'California': 38332521,
                    'Texas': 26448193,
                    'New York': 19651127,
                    'Florida': 19552860,
                    'Illinois': 12882135}
data = pd.Series(population_dict)

print(data.index)
print(data.keys())
print(data.values)

print(data)

population = pd.Series(population_dict, index=['Ohio', 'Texas'])

print(population)
print(population.index)
print(data['California':'Florida'])
print(data[0:3])

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')
Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')
[38332521 26448193 19651127 19552860 12882135]
California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64
Ohio            NaN
Texas    26448193.0
dtype: float64
Index(['Ohio', 'Texas'], dtype='object')
California    38332521
Texas         26448193
New York      19651127
Florida       19552860
dtype: int64
California    38332521
Texas         26448193
New York      19651127
dtype: int64


In [37]:
area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297,
             'Florida': 170312, 'Illinois': 149995, 'Ohio': 999999}
area = pd.Series(area_dict)

#print(area)
#print(data)

states = pd.DataFrame({'population': data, 'area': area})
#print(states)

#print(states.index)
#print(states.columns)

#print(states['population'])
#print(states.population)

states['density'] = states['population'] / states['area']

print(states)

            population    area     density
California  38332521.0  423967   90.413926
Florida     19552860.0  170312  114.806121
Illinois    12882135.0  149995   85.883763
New York    19651127.0  141297  139.076746
Ohio               NaN  999999         NaN
Texas       26448193.0  695662   38.018740


In [45]:
print(states)

#print(states.values)

print(states.loc['California', 'density'])
print(states.iloc[0,2])
# print(states[0,2]) this is a nope
#print(states.ix['California', 2])
print(states.loc[:, 'population': 'area'])

over_onehund = (states[states['density'] > 100])
print(over_onehund[['population', 'density']])

print(states.loc[states['density'] > 100, ['population', 'density']])

            population    area     density
California  38332521.0  423967   90.413926
Florida     19552860.0  170312  114.806121
Illinois    12882135.0  149995   85.883763
New York    19651127.0  141297  139.076746
Ohio               NaN  999999         NaN
Texas       26448193.0  695662   38.018740
90.41392608386974
90.41392608386974
            population    area
California  38332521.0  423967
Florida     19552860.0  170312
Illinois    12882135.0  149995
New York    19651127.0  141297
Ohio               NaN  999999
Texas       26448193.0  695662
          population     density
Florida   19552860.0  114.806121
New York  19651127.0  139.076746
          population     density
Florida   19552860.0  114.806121
New York  19651127.0  139.076746


In [26]:
name = ['Alice', 'Bob', 'Cathy', 'Doug']
age = [25, 45, 37, 19]
weight = [55.0, 85.5, 68.0, 61.5]

ages = pd.Series(age, index=name)
weights = pd.Series(weight, index=name)

#print(ages)
#print(weights)

info = pd.DataFrame({'age': ages, 'weight': weights})

print(info)

       age  weight
Alice   25    55.0
Bob     45    85.5
Cathy   37    68.0
Doug    19    61.5


In [5]:
import numpy as np
name = ['Alice', 'Bob', 'Cathy', 'Doug']
age = [25, 45, 37, 19]
weight = [55.0, 85.5, 68.0, 61.5]

x = np.zeros(4, dtype = int)
print(x)

data = np.zeros(4, dtype={'names':('name', 'age', 'weight'),
                          'formats':('U10', 'i4', 'f8')})
print(data)
print(data.dtype)

data['name'] = name

data['age'] = age
data['weight'] = weight
print(data)

print(data['name'])
print(data[0])

print(data['age'] < 30)

print(data[(data['age'] < 30)])

data[data['age']< 30]['name']


[0 0 0 0]
[('', 0, 0.) ('', 0, 0.) ('', 0, 0.) ('', 0, 0.)]
[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')]
[('Alice', 25, 55. ) ('Bob', 45, 85.5) ('Cathy', 37, 68. )
 ('Doug', 19, 61.5)]
['Alice' 'Bob' 'Cathy' 'Doug']
('Alice', 25, 55.)
[ True False False  True]
[('Alice', 25, 55. ) ('Doug', 19, 61.5)]


array(['Alice', 'Doug'], dtype='<U10')

In [9]:
import pandas as pd 

data = pd.Series([23, 45, 87, 32], index = ['bob', 'carrie', 'dave', 'apple'])

print(data)
print(data[0])
print(data['bob'])

bob       23
carrie    45
dave      87
apple     32
dtype: int64
23
23


In [13]:
population_dict = {'California': 38332521,
                    'Texas': 26448193,
                    'New York': 19651127,
                    'Florida': 19552860,
                    'Illinois': 12882135}

data = pd.Series(population_dict)

print(data.index)
print(data.keys())
print(data.values)

print(data)

population = pd.Series(population_dict, index=['Ohio', 'Texas'])

print(population)
print(population.index)

print(data['California'])
print(data[0:3])

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')
Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')
[38332521 26448193 19651127 19552860 12882135]
California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64
Ohio            NaN
Texas    26448193.0
dtype: float64
Index(['Ohio', 'Texas'], dtype='object')
38332521
California    38332521
Texas         26448193
New York      19651127
dtype: int64


In [18]:
area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297,
             'Florida': 170312, 'Illinois': 149995, 'Ohio': 999999}
area = pd.Series(area_dict)

print(area)
print(data)

states = pd.DataFrame({'population': data, 'area': area})
print(states)

#print(states.index)
#print(states.columns)

print(states['New York':])

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Ohio          999999
dtype: int64
California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64
            population    area
California  38332521.0  423967
Florida     19552860.0  170312
Illinois    12882135.0  149995
New York    19651127.0  141297
Ohio               NaN  999999
Texas       26448193.0  695662
            population    area
California  38332521.0  423967
Florida     19552860.0  170312
Illinois    12882135.0  149995
New York    19651127.0  141297
Ohio               NaN  999999
Texas       26448193.0  695662


In [19]:
print(states)

#print(states.values)

print(states.loc['California', 'density'])
print(states.iloc[0, 2])
# print(states[0,2]) this is a nope
# print(states.ix['California', 2])
print(states.loc[:, 'population':'area'])

over_onehund = (states[states['density'] > 100])
print(over_onehund[['population', 'density']])

print()

            population    area
California  38332521.0  423967
Florida     19552860.0  170312
Illinois    12882135.0  149995
New York    19651127.0  141297
Ohio               NaN  999999
Texas       26448193.0  695662
[[38332521.   423967.]
 [19552860.   170312.]
 [12882135.   149995.]
 [19651127.   141297.]
 [      nan   999999.]
 [26448193.   695662.]]


In [23]:
name = ['Alice', 'Bob', 'Cathy', 'Doug']

age = [25, 45, 37, 19]

weight = [55.0, 85.5, 68.0, 61.5]

ages = pd.Series(age, index=name)
weights = pd.Series(weight, index=name)

#print(ages)
#print(weights)

Alice    25
Bob      45
Cathy    37
Doug     19
dtype: int64
Alice    55.0
Bob      85.5
Cathy    68.0
Doug     61.5
dtype: float64


In [ ]:
import pandas as pd 

df_single_level_cols = pd.DataFrame([[0, 1], [2, 3]],
                                    index )